import 'package:hive/hive.dart';

class QRHistoryModel extends HiveObject {
  final String id;
  final String data;
  final QRType type;
  final DateTime createdAt;
  final bool isFavorite;
  final bool isGenerated; // true if generated by user, false if scanned
  final String? title; // Optional title for the QR code

  QRHistoryModel({
    required this.id,
    required this.data,
    required this.type,
    required this.createdAt,
    this.isFavorite = false,
    required this.isGenerated,
    this.title,
  });

  QRHistoryModel copyWith({
    String? id,
    String? data,
    QRType? type,
    DateTime? createdAt,
    bool? isFavorite,
    bool? isGenerated,
    String? title,
  }) {
    return QRHistoryModel(
      id: id ?? this.id,
      data: data ?? this.data,
      type: type ?? this.type,
      createdAt: createdAt ?? this.createdAt,
      isFavorite: isFavorite ?? this.isFavorite,
      isGenerated: isGenerated ?? this.isGenerated,
      title: title ?? this.title,
    );
  }
}

enum QRType {
  text,
  url,
  phone,
  wifi,
  email,
  sms,
  vcard,
  other,
}

// Custom Hive Adapter for QRHistoryModel
class QRHistoryModelAdapter extends TypeAdapter<QRHistoryModel> {
  @override
  final int typeId = 0;

  @override
  QRHistoryModel read(BinaryReader reader) {
    final id = reader.readString();
    final data = reader.readString();
    final type = QRType.values[reader.readInt()];
    final createdAt = DateTime.parse(reader.readString());
    final isFavorite = reader.readBool();
    final isGenerated = reader.readBool();
    final titleStr = reader.readString();
    return QRHistoryModel(
      id: id,
      data: data,
      type: type,
      createdAt: createdAt,
      isFavorite: isFavorite,
      isGenerated: isGenerated,
      title: titleStr.isEmpty ? null : titleStr,
    );
  }

  @override
  void write(BinaryWriter writer, QRHistoryModel obj) {
    writer.writeString(obj.id);
    writer.writeString(obj.data);
    writer.writeInt(obj.type.index);
    writer.writeString(obj.createdAt.toIso8601String());
    writer.writeBool(obj.isFavorite);
    writer.writeBool(obj.isGenerated);
    writer.writeString(obj.title ?? '');
  }
}

